version: "3.1"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGODB_DATABASE: tweeeht
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - 27017:27017
